name: Greet someone

inputs:
  who-to-greet:
    description: Person to greet
    type: string
    default: 'world'
    required: true

outputs:
  time:
    description: 'The time we greeted'

runs:
  using: 'docker'
  image: 'DockerFile
  args:
    - ${ inputs.who-to-greet }
