name: Hello World Docker

on:
  push:
    branches: [main]
    paths: [hello-world-docker-action/**]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: RUn docker container
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: 'Gustavo-1300'

      - name: Output time
        run: echo "The time was ${{ steps.hello-action.outputs.time }}"
